### ISSUE TITLE
[10.0] AttributeError: 'res.partner' object has no attribute 'comment_template_id'

### ISSUE THREAD

**Issue by imbarbudiman** [OCA/sale-reporting#111]
I used **sale_comment_template** on Odoo 10, when I chose Customer in Sales Order an error occurred:

`
Traceback (most recent call last):
  File "/home/imbar/opt/odoo10-git/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/imbar/opt/odoo10-git/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/imbar/opt/odoo10-git/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/imbar/opt/odoo10-git/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/imbar/opt/odoo10-git/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/imbar/opt/odoo10-git/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/home/imbar/opt/odoo10-git/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/home/imbar/opt/odoo10-git/addons/web/controllers/main.py", line 895, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/imbar/opt/odoo10-git/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/imbar/opt/odoo10-git/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/imbar/opt/odoo10-git/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/imbar/opt/odoo10-git/odoo/models.py", line 5555, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/imbar/opt/odoo10-git/odoo/models.py", line 5453, in _onchange_eval
    method_res = method(self)
  File "/xxxxxxxxxxxxxxxxxxxx/sale_comment_template/models/sale_order.py", line 47, in onchange_partner_id_sale_comment
    comment_template = self.partner_id.comment_template_id
AttributeError: 'res.partner' object has no attribute 'comment_template_id'
`

I searched with VS Code, I couldn't find **comment_template_id** in all modules

**Comment by imbarbudiman** [comment]
solved: make sure to use the latest version [invoice_comment_template](https://apps.odoo.com/apps/modules/10.0/invoice_comment_template/) which already has **res_partner.py**
