### ISSUE TITLE
[14.0] [sale_comment_template] unable to generate invoice form order or quotation

### ISSUE THREAD

**Issue by ygol** [OCA/sale-reporting#129]
## Module
sale_comment_template

## Describe the bug
A. Not possible to create a sale order
B. Not possible to generate an invoice from the sale order

## To Reproduce
case A
1. create an order.
2. get error number 1

case B
1. edit an existing order.
2. add comments
3. click on "create invoice"
4. get error number 2

**Expected behavior**
an invoice is created with the comments defined in the order

**Additional context**

```
Error number 1:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1392, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1384, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/models.py", line 6253, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/odoo/src/odoo/odoo/models.py", line 5995, in _onchange_eval
    method_res = method(self)
  File "/home/odoo/src/user/sale_comment_template/models/sale_order.py", line 48, in onchange_partner_id_sale_comment
    comment_template = self.partner_id.property_comment_template_id
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'res.partner' object has no attribute 'property_comment_template_id'
```

```
Error number 2:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1396, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1384, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/addons/sale/wizard/sale_make_invoice_advance.py", line 161, in create_invoices
    sale_orders._create_invoices(final=self.deduct_down_payments)
  File "/home/odoo/src/odoo/addons/sale/models/sale.py", line 787, in _create_invoices
    moves = self.env['account.move'].sudo().with_context(default_move_type='out_invoice').create(invoice_vals_list)
  File "<decorator-gen-174>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/addons/account/models/account_move.py", line 1968, in create
    vals_list = self._move_autocomplete_invoice_lines_create(vals_list)
  File "/home/odoo/src/odoo/addons/account/models/account_move.py", line 1918, in _move_autocomplete_invoice_lines_create
    move = self_ctx.new(vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 5515, in new
    record._update_cache(values, validate=False)
  File "/home/odoo/src/odoo/odoo/models.py", line 5157, in _update_cache
    raise ValueError("Invalid field %r on model %r" % (e.args[0], self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'comment_template1_id' on model 'account.move'
```

**Comment by ygol** [comment]
maybe got old version. will double check
