### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by willievmobile** [OCA/sale-reporting#263]
Ive tried multiple times to install the module and it keep getting errors

17.0-mig-sale_layout_category_hide_detail

ive tried to get the app installed but it just wont work- i had the hosting co update odoo and try install it and they also get the following error: https://prnt.sc/cS4Xb0Uo0LRE

Could you please tell me what update of odoo is required? i really really need this for our sales orders and ive been struggling for weeks and i just cant get it working?

**Comment by willievmobile** [comment]
Ive tried for weeks updating and getting my hosting co to update odoo 17 but  jsut cant get this module to work.
the error:
https://prnt.sc/cS4Xb0Uo0LRE
ive been stuck on this for weeks

**Comment by willievmobile** [comment]
`RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/cloudclusters/odoo/odoo/http.py", line 1765, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/cloudclusters/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/cloudclusters/odoo/odoo/http.py", line 1792, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/cloudclusters/odoo/odoo/http.py", line 1996, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/cloudclusters/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    result = endpoint(**request.params)
  File "/cloudclusters/odoo/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/cloudclusters/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/cloudclusters/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/cloudclusters/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/cloudclusters/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 459, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 583, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/cloudclusters/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 205, in load_module_graph
    registry.init_models(env.cr, model_names, {'module': package.name}, new_install)
  File "/cloudclusters/odoo/odoo/modules/registry.py", line 576, in init_models
    env['ir.model']._reflect_models(model_names)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_model.py", line 431, in _reflect_models
    self.env['ir.model.data']._update_xmlids(data_list)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_model.py", line 2264, in _update_xmlids
    self._xmlid_lookup.cache.add_value(self, f"{module}.{name}", cache_value=(model, res_id))
AttributeError: 'function' object has no attribute 'cache'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@https://odoo-169327-0.cloudclusters.net/web/assets/a143fff/web.assets_web.min.js:2876:319
    makeErrorFromResponse@https://odoo-169327-0.cloudclusters.net/web/assets/a143fff/web.assets_web.min.js:2879:163
    jsonrpc/promise</<@https://odoo-169327-0.cloudclusters.net/web/assets/a143fff/web.assets_web.min.js:2883:34`

Thats the full error just in case it helps

**Comment by willievmobile** [comment]
@jeroenev
Sorry to @ you but im really desperate?

**Comment by jeroenev** [comment]
I'm not sure, but if I look at your error this line looks different in my Odoo codebase:

```self._xmlid_lookup.__cache__.add_value(self, f"{module}.{name}", cache_value=(model, res_id))```
instead of ```self._xmlid_lookup.cache.add_value(self, f"{module}.{name}", cache_value=(model, res_id))```
but could also be the _xmlid_lookup function that's altered somewhere in your local Odoo?
``` python
    @api.model
    @tools.ormcache('xmlid')
    def _xmlid_lookup(self, xmlid: str) -> tuple:
        """Low level xmlid lookup
        Return (id, res_model, res_id) or raise ValueError if not found
        """
        module, name = xmlid.split('.', 1)
        query = "SELECT model, res_id FROM ir_model_data WHERE module=%s AND name=%s"
        self.env.cr.execute(query, [module, name])
        result = self.env.cr.fetchone()
        if not (result and result[1]):
            raise ValueError('External ID not found in the system: %s' % xmlid)
        return result
```
is what the default Odoo version looks like.

I'm not sure how much I can help aside from that, since your error doesn't really hit the `sale_layout_category_hide_detail` module at all, seems like the stack-trace only hits your Odoo codebase, it definitely seems like there's something wrong there.

maybe you can also try "Update App List" under Apps module (in debug mode)?

**Comment by willievmobile** [comment]
Hey @jeroenev 
Thanks for that, yes ive updated the app list ive reinstalled the odoo instances etc and i jsut cant get it to work. its litelarly the only module i need to get working :(

**Comment by jeroenev** [comment]
do you get a similar error trying to install other apps?

**Comment by willievmobile** [comment]
No not at all- i have tried a new install with no other apps and its the same thing. then i tried installing some other apps that do various things like merging quotes etc and they all work fine its just this one that doesnt want to work. and if i force install it then odoo crashes......

**Comment by jeroenev** [comment]
really looks like an issue with _xmlid_lookup
is that inherited somewhere?
if yes, does it have 
``` python
    @api.model
    @tools.ormcache('xmlid')
 ``` 
attached?

**Comment by willievmobile** [comment]
i really have no idea what that all means :(

**Comment by jeroenev** [comment]
you don't have any developer working on the project?

**Comment by willievmobile** [comment]
Hey no im doing the server etc etc myself. I can normally help myself around code and linux but web backends etc is a bit foreign to me. i didnt even know how to properly get help here lol.
I have a couple of odoo instances running for various of my companies. normally im able to figure things out but this has stumped me completely. and its really made our day to day sales a major pain... 
Id be happy to pay somone to assist if thats what is needed, i just need to get this working,  as i migrated like 1000 products into this instance already :(

**Comment by jeroenev** [comment]
Does the error also occur if you create a new database? Or only on your current database?

**Comment by willievmobile** [comment]
So i installed a fresh instance on the cloudclusters servers and tried and it does exaclty the same thing
`RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/cloudclusters/odoo/odoo/http.py", line 1732, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/cloudclusters/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/cloudclusters/odoo/odoo/http.py", line 1759, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/cloudclusters/odoo/odoo/http.py", line 1960, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/cloudclusters/odoo/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    result = endpoint(**request.params)
  File "/cloudclusters/odoo/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/cloudclusters/odoo/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/cloudclusters/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/cloudclusters/odoo/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/cloudclusters/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-76>", line 2, in button_immediate_install
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 459, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/cloudclusters/odoo/odoo/addons/base/models/ir_module.py", line 583, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/cloudclusters/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/cloudclusters/odoo/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/cloudclusters/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/cloudclusters/odoo/odoo/tools/convert.py", line 627, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/cloudclusters/odoo/odoo/tools/convert.py", line 693, in convert_xml_import
    obj.parse(doc.getroot())
  File "/cloudclusters/odoo/odoo/tools/convert.py", line 613, in parse
    self._tag_root(de)
  File "/cloudclusters/odoo/odoo/tools/convert.py", line 567, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing None:8
Error while parsing or validating view:

Element '<xpath expr="//t[@t-foreach=&#39;lines&#39;]//span[contains(@t-out, &#39;taxes&#39;)]">' cannot be located in parent view

View error context:
{'file': '/cloudclusters/odoo/odoo/addons/sale_layout_category_hide_detail/views/invoice_report_templates.xml',
 'line': 2,
 'name': 'report_invoice_document_hide_detail',
 'view': ir.ui.view(2779,),
 'view.model': False,
 'view.parent': ir.ui.view(717,),
 'xmlid': 'report_invoice_document_hide_detail'}


The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@https://odoo-170238-0.cloudclusters.net/web/assets/3da11de/web.assets_web.min.js:2869:319
    makeErrorFromResponse@https://odoo-170238-0.cloudclusters.net/web/assets/3da11de/web.assets_web.min.js:2872:163
    jsonrpc/promise</<@https://odoo-170238-0.cloudclusters.net/web/assets/3da11de/web.assets_web.min.js:2876:34`

**Comment by willievmobile** [comment]
@jeroenev i installed a new DB, same issue. ive tried everything i can think of. as i said its only this app so i dont know what else to try. would you possibly be willing to log into a isntace and have look? im banging my head on a wall and everyday this isnt working everyone is jsut getting really irritated with odoo :(
