### ISSUE TITLE
Error Installation Sale layout category hide detail

### ISSUE THREAD

**Issue by kacholatino** [OCA/sale-reporting#273]
## Module
Sale layout category hide detail

## Describe the bug
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo16/odoo/odoo/http.py", line 1591, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo16/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo16/odoo/odoo/http.py", line 1618, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo16/odoo/odoo/http.py", line 1822, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo16/odoo/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo16/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo16/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo16/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo16/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo16/odoo/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo16/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "/opt/odoo16/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo16/odoo/odoo/addons/base/models/ir_module.py", line 468, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo16/odoo/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-16>", line 2, in new
  File "/opt/odoo16/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/opt/odoo16/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo16/odoo/odoo/modules/loading.py", line 488, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo16/odoo/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo16/odoo/odoo/modules/loading.py", line 231, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/opt/odoo16/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/odoo16/odoo/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/opt/odoo16/odoo/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo16/odoo/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/opt/odoo16/odoo/odoo/tools/convert.py", line 709, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing None:8
Ocurrió un error al validar la vista:

El elemento '<xpath expr="//tbody[hasclass(&#39;invoice_tbody&#39;)]//tr[hasclass(&#39;is-subtotal&#39;, &#39;text-end&#39;)]">' no puede ser localizado en la vista padre

View error context:
{'file': '/opt/odoo16/odoo-custom-addons/sale_layout_category_hide_detail/views/invoice_report_templates.xml',
 'line': 2,
 'name': 'report_invoice_document_hide_detail',
 'view': ir.ui.view(3563,),
 'view.model': False,
 'view.parent': ir.ui.view(771,),
 'xmlid': 'report_invoice_document_hide_detail'}

The above server error caused the following client error:
RPC_ERROR://odoo.itechcloudservices.com/web/assets/5611-f888c5c/web.assets_backend.min.js:991:163)
    at XMLHttpRequest.<anonymous> (https://odoo.itechcloudservices.com/web/assets/5611-f888c5c/web.assets_backend.min.js:999:13)

## To Reproduce
**Affected versions**: 16.0

**Comment by pedrobaeza** [comment]
Your installation seems to have some changes incompatible with the module, but it's not a problem of the module itself. You should check the exact error and see which other module / manual modification is breaking it.

Closing as it's not a problem of this module.

**Comment by kacholatino** [comment]
Gracias Pedro.
