### ISSUE TITLE
Error in report_saleorder.xml template

### ISSUE THREAD

**Issue by readylan** [OCA/sale-reporting#277]
## Module
sale_comment_template

## Describe the bug
Installation is ok, but when you try to print a sale order with comments it raises an error because de template has an erroneous expression (<div t-raw="doc.render_comment(comment_template_top)" />)

## To Reproduce
**Affected versions**: 14.0

1. Install module
2. Create a template from Sales > Configuration > Comments..
3. Create / edit a sale order and link created comments above.
4. Print sale order report

**Expected behavior**
Sale order report must print configured "Comments" (on top/bottom as defined) but it raises an error:
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 331, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_sale_report_saleorder_document_1838
  File "<template>", line 2, in body_call_content_1836
  File "<template>", line 1, in foreach_1835
AttributeError: 'sale.order' object has no attribute 'render_comment'

**Additional context**
There are other related modules (account_comment_template) running fine. The problem is in module template (sale_comment_template/views/report_saleorder.xml):
                <div t-raw="doc.render_comment(comment_template_top)" /> THIS ONE FAILS
                <div t-raw="comment_template_top.text" /> THIS ONE RUNS

**Comment by readylan** [comment]
the current code that fails:
`<div t-raw="doc.render_comment(comment_template_top)" />`
the sugested code than runs:
`<div t-raw="comment_template_top.text" />`
