### ISSUE TITLE
[11.0 -> 12.0] Fail to migrate sale_layout_category_hide_detail

### ISSUE THREAD

**Issue by Danoolo** [OCA/sale-reporting#75]
Hi guys!!...when trying to migrate a 11.0 db backup i found this error:

2019-11-15 21:52:19,662 32511 CRITICAL AP12.0a odoo.service.server: Failed to initialize database `AP12.0a`. 
Traceback (most recent call last):
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/service/server.py", line 1118, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/loading.py", line 476, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/loading.py", line 360, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/loading.py", line 194, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/modules/migration.py", line 199, in migrate_module
    migrate(self.cr, installed_version)
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib-3.0.0-py3.6.egg/openupgradelib/openupgrade.py", line 1691, in wrapped_function
    if use_env2 else cr, version)
  File "/home/gloobal/PycharmProjects/Developments/gloobal-addons/oca_modules/sale-reporting/sale_layout_category_hide_detail/migrations/12.0.1.0.0/pre-migration.py", line 17, in migrate
    """,
  File "/usr/local/lib/python3.6/dist-packages/openupgradelib-3.0.0-py3.6.egg/openupgradelib/openupgrade.py", line 1158, in logged_query
    cr.execute(query, args)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/gloobal/PycharmProjects/Developments/migration/openupgrade/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column "show_details" of relation "sale_order_line" does not exist

Worth mentioning this module was installed in previous version...this error tells me that new fields are not created when this sql update is running...any ideas?..thanks in advance.

**Comment by pedrobaeza** [comment]
Indeed, it should be executed post update:

6430d9232f0d8b7c5afb77845c811a0306fc4016
